name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Node Setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install packages
        run: yarn install

      - name: Build website
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve build
          wait-on: 'http://localhost:3000'

      - name: Copy files to S3
        env:
          BUCKET: ${{ secrets.AWS_BUCKET }}
        run: |
          aws s3 sync ./build s3://${BUCKET} --delete

      - name: Invalidate CloudFront Cache
        env:
          ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${ID} --paths '/*'

